In [1]:
%matplotlib inline
import sys
print(sys.version)
import numpy as np
print(np.__version__)
import pandas as pd
print(pd.__version__)
import matplotlib.pyplot as plt
from pandas_datareader import data, wb
from datetime import timedelta

3.5.1 |Anaconda 2.4.1 (x86_64)| (default, Dec  7 2015, 11:24:55)
[GCC 4.2.1 (Apple Inc. build 5577)]
1.11.0
0.18.0

In [2]:
teams = pd.read_csv('Home_Data.csv')
del teams['Unnamed: 0']
teams.set_index('stationID')

                team isclosable  altitude
stationID
KSLI          angels      False       160
KEFD          astros       True        38
KOAK       athletics      False        42
KYYZ       blue_jays       True       247
KATL          braves      False      1050
KMKE         brewers       True       593
KCPS       cardinals      False       455
KORD            cubs      False       596
KPHX         d-backs       True      1082
KCQT         dodgers      False       267
KSFO          giants      False        63
KBKL         indians      False       582
KBFI        mariners       True        10
KMIA         marlins       True        15
KLGA            mets      False        54
KDCA       nationals      False        25
KBWI         orioles      False       130
KSAN          padres      False        13
KPHL        phillies      False         9
KPIT         pirates      False       743
KDAL         rangers      False       616
KSPG            rays       True        44
KBOS         red_sox      False        20
KLUK            reds      False       683
KDEN         rockies      False      5183
KMKC          royals      False       750
KDET          tigers      False       596
KMSP           twins      False       812
KMDW       white_sox      False       596
KNYC         yankees      False        54

In [3]:
weather = pd.read_csv('Clean_Weather.csv')
del weather['Unnamed: 0']
weather.set_index('stationID')

                           gmt  tempF  relhum  altibarom
stationID
KLGA       2015-10-11 04:51:00     57      62      30.07
KLGA       2015-10-11 03:51:00     57      57      30.08
KLGA       2015-10-11 02:51:00     57      55      30.08
KLGA       2015-10-11 01:51:00     59      48      30.07
KLGA       2015-10-11 00:51:00     60      46      30.09
KLGA       2015-10-10 23:51:00     61      36      30.06
KLGA       2015-10-10 22:51:00     63      34      30.06
KLGA       2015-10-10 21:51:00     63      35      30.06
KLGA       2015-10-10 20:51:00     64      34      30.07
KLGA       2015-10-10 19:51:00     63      37      30.09
KLGA       2015-10-10 18:51:00     62      38      30.11
KLGA       2015-10-10 17:51:00     60      40      30.12
KLGA       2015-10-10 16:51:00     59      44      30.13
KLGA       2015-10-10 15:51:00     57      49      30.13
KLGA       2015-10-10 14:51:00     55      51      30.13
KLGA       2015-10-10 13:51:00     53      56      30.13
KLGA       2015-10-10 12:51:00     52      61      30.11
KLGA       2015-10-10 11:51:00     52      59      30.08
KLGA       2015-10-10 10:51:00     53      63      30.05
KLGA       2015-10-10 09:51:00     55      59      30.01
KLGA       2015-10-10 08:51:00     55      60      29.97
KLGA       2015-10-10 07:51:00     57      65      29.95
KLGA       2015-10-10 06:51:00     60      67      29.93
KLGA       2015-10-10 05:51:00     62      65      29.89
KLGA       2015-10-10 04:51:00     64      70      29.87
KLGA       2015-10-10 03:51:00     66      75      29.86
KLGA       2015-10-10 02:51:00     66      79      29.84
KLGA       2015-10-10 01:51:00     66      81      29.82
KLGA       2015-10-10 00:51:00     66      84      29.80
KLGA       2015-10-09 23:51:00     66      84      29.78
...                        ...    ...     ...        ...
KSLI       2015-03-31 06:58:00     58      90      30.01
KSLI       2015-03-31 05:58:00     60      88      30.00
KSLI       2015-03-31 04:58:00     61      82      29.99
KSLI       2015-03-31 03:58:00     63      85      29.96
KSLI       2015-03-31 02:58:00     69      64      29.95
KSLI       2015-03-31 01:58:00     71      65      29.94
KSLI       2015-03-31 00:58:00     74      57      29.94
KSLI       2015-03-30 22:58:00     72      60      29.97
KSLI       2015-03-30 21:58:00     73      60      29.99
KSLI       2015-03-30 20:58:00     74      57      30.01
KSLI       2015-03-30 19:58:00     71      58      30.03
KSLI       2015-03-30 18:58:00     66      72      30.04
KSLI       2015-03-30 18:50:00     66      73      30.04
KSLI       2015-03-30 17:58:00     63      86      30.04
KSLI       2015-03-30 17:53:00     60      88      30.05
KSLI       2015-03-30 17:03:00     60      88      30.04
KSLI       2015-03-30 16:58:00     60      88      30.03
KSLI       2015-03-30 15:58:00     59      91      30.03
KSLI       2015-03-30 15:13:00     59      94      30.02
KSLI       2015-03-30 14:58:00     59      93      30.01
KSLI       2015-03-30 13:58:00     59      96      30.00
KSLI       2015-03-30 13:48:00     59     100      30.00
KSLI       2015-03-30 13:13:00     59     100      29.99
KSLI       2015-03-30 12:58:00     59      98      29.99
KSLI       2015-03-30 11:58:00     56     100      29.99
KSLI       2015-03-30 11:43:00     55     100      29.99
KSLI       2015-03-30 10:58:00     57     100      29.99
KSLI       2015-03-30 10:38:00     55     100      30.00
KSLI       2015-03-30 09:58:00     57     100      30.01
KSLI       2015-03-30 08:58:00     58      97      30.02

[160342 rows x 4 columns]

In [4]:
homeweather = pd.merge(weather, teams, how='left')

In [5]:
homeweather.sample(25)

,stationID,gmt,tempF,relhum,altibarom,team,isclosable,altitude
49758,KMIA,2015-05-12 17:53:00,86,59,30.15,marlins,True,15
143940,KEFD,2015-04-24 20:50:00,84,79,29.83,astros,True,38
158158,KSLI,2015-06-09 03:31:00,64,88,29.85,angels,False,160
134112,KSAN,2015-04-29 14:34:00,62,77,29.92,padres,False,13
10509,KNYC,2015-04-16 17:51:00,62,17,30.47,yankees,False,54
582,KLGA,2015-09-19 11:51:00,69,84,29.97,mets,False,54
143074,KEFD,2015-05-31 19:50:00,82,66,30.06,astros,True,38
149552,KSFO,2015-10-05 01:56:00,69,45,29.63,giants,False,63
98140,KPIT,2015-07-14 09:51:00,68,94,29.67,pirates,False,743
136725,KOAK,2015-08-03 20:53:00,71,53,29.98,athletics,False,42
102473,KLUK,2015-09-03 00:13:00,81,67,30.02,reds,False,683
30944,KDCA,2015-06-28 08:52:00,68,83,29.67,nationals,False,25
17733,KPHL,2015-08-29 12:54:00,70,66,30.23,phillies,False,9
137741,KOAK,2015-06-27 04:53:00,60,80,29.94,athletics,False,42
150242,KSFO,2015-09-06 22:56:00,84,16,29.94,giants,False,63
48877,KMIA,2015-06-14 13:53:00,82,68,30.08,marlins,True,15
156016,KSLI,2015-08-18 04:33:00,69,88,29.90,angels,False,160
93069,KCPS,2015-06-29 16:53:00,77,69,29.86,cardinals,False,455
147992,KPHX,2015-05-25 20:51:00,86,19,29.89,d-backs,True,1082
89064,KDET,2015-05-05 14:05:00,53,48,30.30,tigers,False,596
123844,KCQT,2015-04-23 01:47:00,64,63,29.88,dodgers,False,267
109304,KDAL,2015-08-06 02:53:00,96,39,29.85,rangers,False,616
67278,KMDW,2015-04-14 13:53:00,52,44,30.27,white_sox,False,596
125559,KBFI,2015-08-31 06:53:00,64,61,29.99,mariners,True,10
49033,KMIA,2015-06-09 10:31:00,77,83,30.00,marlins,True,15

In [6]:
homeweather['localbarom'] = homeweather['altibarom'] - homeweather['altitude']/1000

In [10]:
homeweather.sample(25)

,stationID,gmt,tempF,relhum,altibarom,team,isclosable,altitude,localbarom
58926,KMSP,2015-07-25 01:53:00,84,63,29.83,twins,False,812,29.018
92899,KCPS,2015-07-04 11:41:00,66,90,29.96,cardinals,False,455,29.505
113594,KDEN,2015-09-27 22:53:00,88,12,29.98,rockies,False,5183,24.797
89360,KDET,2015-04-23 19:53:00,36,50,29.97,tigers,False,596,29.374
80779,KMKE,2015-08-10 02:52:00,70,90,29.93,brewers,True,593,29.337
55112,KMKC,2015-05-21 18:54:00,63,50,30.26,royals,False,750,29.510
138527,KOAK,2015-05-28 20:53:00,57,74,30.06,athletics,False,42,30.018
142888,KEFD,2015-06-09 08:50:00,78,74,29.95,astros,True,38,29.912
81648,KMKE,2015-07-07 05:52:00,73,84,29.83,brewers,True,593,29.237
111172,KDAL,2015-05-28 15:53:00,79,72,30.09,rangers,False,616,29.474
24257,KBWI,2015-08-06 10:54:00,68,78,29.97,orioles,False,130,29.840
96445,KPIT,2015-09-18 02:51:00,69,68,30.07,pirates,False,743,29.327
77719,KORD,2015-05-11 09:51:00,48,93,29.86,cubs,False,596,29.264
10345,KNYC,2015-04-21 14:18:00,54,86,29.66,yankees,False,54,29.606
487,KLGA,2015-09-23 03:51:00,66,57,30.24,mets,False,54,30.186
139989,KOAK,2015-04-04 14:53:00,45,86,30.09,athletics,False,42,30.048
22536,KBWI,2015-10-07 16:54:00,69,65,30.05,orioles,False,130,29.920
76431,KORD,2015-06-22 08:51:00,71,87,29.96,cubs,False,596,29.364
67757,KBKL,2015-10-10 02:53:00,57,64,30.14,indians,False,582,29.558
120097,KCQT,2015-08-31 01:47:00,80,54,29.82,dodgers,False,267,29.553
19721,KPHL,2015-06-22 19:54:00,90,38,30.02,phillies,False,9,30.011
97775,KPIT,2015-07-27 19:51:00,84,46,30.01,pirates,False,743,29.267
134408,KSAN,2015-04-19 04:51:00,64,76,29.98,padres,False,13,29.967
41734,KSPG,2015-08-04 06:53:00,80,87,29.98,rays,True,44,29.936
87167,KDET,2015-07-05 13:53:00,70,61,30.12,tigers,False,596,29.524

In [8]:
homeweather.to_csv('HomeWeatherData.csv')